DROP TABLE if EXISTS url_checks;
DROP TABLE if EXISTS urls;

CREATE TABLE urls (
    id bigint generated by default as identity unique not null,
    name varchar(255),
    created_at timestamp not null,
    last_check timestamp
);

CREATE TABLE url_checks (
    id bigint generated by default as identity unique not null,
    url_id bigint not null,
    status_code smallint,
    h1 varchar(255),
    title  varchar(255),
    description text,
    created_at timestamp not null
);

ALTER TABLE url_checks
add foreign key (url_id) references urls (id)
on delete cascade;